#' Write a STILT simulation configuration file in YAML format
#' @author James Mineau
#'
#' Writes a YAML configuration file for STILT simulations.
#' The configuration file contains all the necessary parameters for reproducing a STILT simulation.
#'
#' @import yaml
#' @export

write_config <- function(
  # System configuration
  stilt_wd,
  output_wd,
  # Receptor placement
  r_time,
  r_lati,
  r_long,
  r_zagl,
  # Footprint calculation methods
  hnf_plume,
  projection,
  smooth_factor,
  time_integrate,
  xmn,
  xmx,
  xres,
  ymn,
  ymx,
  yres,
  foot_id,
  # Meteorological data input
  met_path,
  met_file_format,
  met_file_tres,
  met_subgrid_buffer,
  met_subgrid_enable,
  met_subgrid_levels,
  n_met_min,
  # Model control
  n_hours,
  numpar,
  rm_dat,
  run_foot,
  run_trajec,
  simulation_id,
  timeout,
  varsiwant,
  # Transport and dispersion
  capemin,
  cmass,
  conage,
  cpack,
  delt,
  dxf,
  dyf,
  dzf,
  efile,
  emisshrs,
  frhmax,
  frhs,
  frme,
  frmr,
  frts,
  frvs,
  hscale,
  ichem,
  idsp,
  initd,
  k10m,
  kagl,
  kbls,
  kblt,
  kdef,
  khinp,
  khmax,
  kmix0,
  kmixd,
  kmsl, 
  kpuff,
  krand,
  krnd,
  kspl,
  kwet,
  kzmix,
  maxdim,
  maxpar,
  mgmin,
  mhrs,
  nbptyp,
  ncycl,
  ndump,
  ninit,
  nstr,
  nturb,
  nver,
  outdt,
  p10f,
  pinbc,
  pinpf,
  poutf,
  qcycle,
  rhb,
  rht,
  splitf,
  tkerd,
  tkern,
  tlfrac,
  tout,
  tratio,
  tvmix,
  veght,
  vscale,
  vscaleu,
  vscales,
  w_option,
  wbbh,
  wbwf,
  wbwr,
  wvert,
  z_top,
  zicontroltf,
  ziscale,
  # Transport error calculations
  siguverr,
  tluverr,
  zcoruverr,
  horcoruverr,
  sigzierr,
  tlzierr,
  horcorzierr,
  # User defined functions
  before_footprint,
  # Additional parameters
  file,
  ...
) {
  require(yaml)

  config <- list(
    system = list(
      project = basename(stilt_wd),
      stilt_wd = stilt_wd,
      output_wd = output_wd
    ),
    model = list(
      n_hours = n_hours,
      numpar = numpar,
      rm_dat = rm_dat,
      run_foot = run_foot,
      run_trajec = run_trajec,
      simulation_id = simulation_id,
      timeout = timeout,
      varsiwant = varsiwant
    ),
    receptors = list(
      time = r_time,
      lati = r_lati,
      long = r_long,
      zagl = r_zagl
    ),
    footprint = list(
      hnf_plume = hnf_plume,
      projection = projection,
      smooth_factor = smooth_factor,
      time_integrate = time_integrate,
      xmn = xmn,
      xmx = xmx,
      xres = xres,
      ymn = ymn,
      ymx = ymx,
      yres = yres,
      foot_id = foot_id
    ),
    met = list(
      met_path = met_path,
      met_file_format = met_file_format,
      met_file_tres = met_file_tres,
      met_subgrid_enable = met_subgrid_enable,
      met_subgrid_buffer = met_subgrid_buffer,
      met_subgrid_levels = met_subgrid_levels,
      n_met_min = n_met_min
    ),
    transport = list(
      capemin = capemin,
      cmass = cmass,
      conage = conage,
      cpack = cpack,
      delt = delt,
      dxf = dxf,
      dyf = dyf,
      dzf = dzf,
      efile = efile,
      emisshrs = emisshrs,
      frhmax = frhmax,
      frhs = frhs,
      frme = frme,
      frmr = frmr,
      frts = frts,
      frvs = frvs,
      hscale = hscale,
      ichem = ichem,
      idsp = idsp,
      initd = initd,
      k10m = k10m,
      kagl = kagl,
      kbls = kbls,
      kblt = kblt,
      kdef = kdef,
      khinp = khinp,
      khmax = khmax,
      kmix0 = kmix0,
      kmixd = kmixd,
      kmsl = kmsl,
      kpuff = kpuff,
      krand = krand,
      krnd = krnd,
      kspl = kspl,
      kwet = kwet,
      kzmix = kzmix,
      maxdim = maxdim,
      maxpar = maxpar,
      mgmin = mgmin,
      mhrs = mhrs,
      nbptyp = nbptyp,
      ncycl = ncycl,
      ndump = ndump,
      ninit = ninit,
      nstr = nstr,
      nturb = nturb,
      nver = nver,
      outdt = outdt,
      p10f = p10f,
      pinbc = pinbc,
      pinpf = pinpf,
      poutf = poutf,
      qcycle = qcycle,
      rhb = rhb,
      rht = rht,
      splitf = splitf,
      tkerd = tkerd,
      tkern = tkern,
      tlfrac = tlfrac,
      tout = tout,
      tratio = tratio,
      tvmix = tvmix,
      veght = veght,
      vscale = vscale,
      vscaleu = vscaleu,
      vscales = vscales,
      w_option = w_option,
      wbbh = wbbh,
      wbwf = wbwf,
      wbwr = wbwr,
      wvert = wvert,
      z_top = z_top,
      zicontroltf = zicontroltf,
      ziscale = ziscale
    ),
    error = list(
      siguverr = siguverr,
      tluverr = tluverr,
      zcoruverr = zcoruverr,
      horcoruverr = horcoruverr,
      sigzierr = sigzierr,
      tlzierr = tlzierr,
      horcorzierr = horcorzierr
    ),
    user_funcs = list(
      before_footprint = before_footprint
    ),
    metadata = list(
      time_created = format(Sys.time(), "%Y-%m-%dT%H:%M:%SZ"),
      git_url = system('git config --get remote.origin.url', intern = TRUE),
      git_commit = find_git_commit_id()
    )
  )

  # Generate the YAML string from the config list
  yaml_str <- as.yaml(config, indent.mapping.sequence = TRUE)
  yaml_str <- gsub(" (\\.na|~)\n", " null\n", yaml_str)  # Replace .na or ~ with null
  yaml_str <- gsub(" yes\n", " true\n", yaml_str)  # Replace yes with true
  yaml_str <- gsub(" no\n", " false\n", yaml_str)  # Replace no with false

  # Write the YAML string to the specified file
  writeLines(yaml_str, file)
}